[package]
name = "rsnake"
version = "0.2.0"
authors = ["Mara Schulke <mara@schulke.xyz>", "Kacper Nitkiewicz <crg1234@gmail.com>"]
edition = "2018"

[dependencies]
piston_window = "0.89.0"
find_folder = "0.3.0"
rand = "0.6.5"
